kind: Service
apiVersion: v1
metadata:
  name: contracts-service
  labels:
    app: contracts-service
  namespace: ikomida
spec:
  selector:
     app: contracts
  ports:
  - protocol: TCP
    port: 1988