name: publish ikomida dev lib to artifact registry on pull request merge
on:
  pull_request_target:
    types:
      - closed
    branches:
      - dev
      - hmlg
      - main

env:
  GAR_LOCATION: us-central1 # # TODO: update region of the Artifact Registry
  GKE_CLUSTER: ikomida-cluster # TODO: update to cluster name
  GKE_ZONE: us-central1-b # TODO: update to cluster zone
  IMAGE: contracts-microservice-image
  TAG: latest

jobs:
  build_and_deploy_ikomida:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ endsWith(github.ref, '/main') && secrets.BUILD_IKOMIDA_PROD_SERVICE_ACOUNT || (endsWith(github.ref, '/hmlg') && secrets.BUILD_IKOMIDA_HMLG_SERVICE_ACOUNT || secrets.BUILD_IKOMIDA_DEV_SERVICE_ACOUNT) }}"
      - name: Setup Docker credentials
        env:
          PROJECT_ID: ${{ steps.auth.outputs.project_id }}
        run: |-
          gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev --project ${PROJECT_ID}
      - name: Setup GKE credentials
        run: |-
          gcloud container clusters get-credentials "${GKE_CLUSTER}" --zone "${GKE_ZONE}"
      - id: Builder
        name: Create docker builder
        run: |-
          docker buildx create --name container --driver docker-container
          docker buildx use container
      - id: Docker-cache
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-latest
          restore-keys: |
            ${{ runner.os }}-buildx-
      - id: Docker
        name: Build & push docker image
        env:
          PROJECT_ID: ${{ steps.auth.outputs.project_id }}
          SERVICE_ACCOUNT: "${{ endsWith(github.ref, '/main') && secrets.BUILD_IKOMIDA_PROD_SERVICE_ACOUNT || (endsWith(github.ref, '/hmlg') && secrets.BUILD_IKOMIDA_HMLG_SERVICE_ACOUNT || secrets.BUILD_IKOMIDA_DEV_SERVICE_ACOUNT) }}"
        run: |-
          DOCKER_IMAGE=${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/docker/${IMAGE}:${TAG}
          echo "Image: ${DOCKER_IMAGE}"
          BASE64_SERVICE_ACCOUNT="$(echo "${SERVICE_ACCOUNT}" | base64)"
          docker buildx build -o type=registry --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache" --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg GOOGLE_SERVICE_ACCOUNT="${BASE64_SERVICE_ACCOUNT}" --build-arg PROJECT_ID="${PROJECT_ID}" --builder=container -t "${DOCKER_IMAGE}" .
      - name: Deploy
        env:
          PROJECT_ID: ${{ steps.auth.outputs.project_id }}
        run: |-
          kubectl get pods
          kubectl -n ikomida delete deploy contracts-microservice || true
          for FILE in k8s/*.yaml; do printf "$(cat $FILE)\n---\n" | envsubst; done | kubectl apply -f -
